# Generated by Django 2.2.3 on 2020-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=10, unique=True)),
                ('car_make', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=10)),
                ('car_registration', models.CharField(max_length=8, unique=True)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_id', models.CharField(max_length=10, unique=True)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('postcode', models.CharField(max_length=7)),
                ('rider_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.CharField(max_length=128)),
            ],
        ),
    ]
