# Generated by Django 2.2.3 on 2020-03-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szchober', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_driver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_rider',
            field=models.BooleanField(default=True),
        ),
    ]
