# Generated by Django 2.2.3 on 2020-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szchober', '0003_auto_20200330_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
