# Generated by Django 2.2.3 on 2020-03-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szchober', '0004_driver_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='szchober.User'),
        ),
    ]
