# Generated by Django 2.2.3 on 2020-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szchober', '0004_userprofile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='forename',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='driver',
            name='review',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='driver',
            name='surname',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='forename',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='rider',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='rider',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='rider',
            name='review',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rider',
            name='surname',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_make',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_registration',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='end',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='start',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rider',
            name='postcode',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
