# Generated by Django 2.2.3 on 2020-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szchober', '0005_auto_20200321_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rider', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_driver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
    ]
